data:
  type: cifar10
  train_dir: ./data/
  test_dir: ./data/
  lsun_categories_train: bedroom_train
  lsun_categories_test: bedroom_test
  img_size: 32
  nchannels: 3
generator:
  name: wgan # resnet1 # fix it to 1: the normal resnet
  # kwargs:
  #   nfilter: 32
  #   nfilter_max: 256
discriminator:
  name: wgan #resnet1 # fix it to 1: the normal resnet
  # kwargs:
  #   nfilter: 32
  #   nfilter_max: 256
z_dist:
  type: gauss
  dim: 256
training:
  gan_type: wgan
  reg_type: none
  reg_param: 0.
  nworkers: 32
  take_model_average: true
  model_average_beta: 0.999
  model_average_reinit: false
  monitoring: tensorboard
  sample_every: 1000
  save_every: 900
  restart_every: -1
  optimizer: adam #rmsprop
  batch_size: 64 ## related to i_size
  lr_g: 0.0001
  lr_d: 0.0001
  out_dir: output/
  out_basename: cifar_wgan_pid0
  pid_type: square
  backup_every: 10000
  inception_every: 10000
  pv: 1.
  iv: 0.
  dv: 0.
  i_size: 64 ## related to batch_size
  i_buffer_factor: 100
  i_buffer_onestep: 64
  momentum_d: 0. ###
  clip_d: 0. ###
  weight_decay_d: 0. ###
  regularize_output_d: 0. ###
  lr_anneal: 1.
  lr_anneal_every: 300000
  d_steps: 1
  equalize_lr: false
test:
  batch_size: 32
  sample_size: 15
  sample_nrow: 5
  use_model_average: true
  compute_inception: false
  conditional_samples: false
interpolations:
  nzs: 10
  nsubsteps: 75
